"""Random podcast name generator module (pure, no app dependencies).

Name generation is weighted so most names combine an adjective with an animal,
some combine an adjective with an object, and a minority pair a combined
objects-and-science noun with a place. All randomness flows through a caller
supplied ``random.Random`` so the module stays importable without any
environment settings and remains fully deterministic under test.
"""

from __future__ import annotations

import random

ADJECTIVES: tuple[str, ...] = (
    "cosmic",
    "lunar",
    "solar",
    "stellar",
    "electric",
    "quantum",
    "temporal",
    "invisible",
    "mysterious",
    "secret",
    "forbidden",
    "forgotten",
    "ancient",
    "modern",
    "rusty",
    "dusty",
    "fuzzy",
    "sleepy",
    "grumpy",
    "lonely",
    "curious",
    "reckless",
    "feral",
    "nervous",
    "awkward",
    "suspicious",
    "dramatic",
    "melancholy",
    "delightful",
    "terrible",
    "magnificent",
    "peculiar",
    "strange",
    "bizarre",
    "ordinary",
    "unremarkable",
    "unlikely",
    "accidental",
    "unlicensed",
    "illegal",
    "questionable",
    "dubious",
    "haunted",
    "enchanted",
    "cursed",
    "blessed",
    "radioactive",
    "unstable",
    "flammable",
    "portable",
    "edible",
    "crispy",
    "soggy",
    "fluffy",
    "sticky",
    "slippery",
    "wobbly",
    "jagged",
    "crooked",
    "wonky",
    "lumpy",
)

ANIMALS: tuple[str, ...] = (
    "badger",
    "raccoon",
    "opossum",
    "otter",
    "ferret",
    "walrus",
    "goose",
    "penguin",
    "platypus",
    "armadillo",
    "capybara",
    "marmot",
    "mongoose",
    "weasel",
    "beaver",
    "yak",
    "llama",
    "alpaca",
    "tortoise",
    "turtle",
    "crow",
    "raven",
    "magpie",
    "pigeon",
    "heron",
    "pelican",
    "flamingo",
    "toucan",
    "ibis",
    "vulture",
    "moose",
    "elk",
    "bison",
    "wombat",
    "koala",
    "quokka",
    "wolverine",
    "porcupine",
    "hedgehog",
    "squirrel",
    "chipmunk",
    "hamster",
    "mouse",
    "vole",
    "shrew",
    "mole",
    "rabbit",
    "hare",
    "fox",
    "coyote",
    "dingo",
    "hyena",
    "meerkat",
    "lemur",
    "baboon",
    "gorilla",
    "orangutan",
    "chimpanzee",
    "sloth",
    "anteater",
    "pangolin",
    "tapir",
    "manatee",
    "narwhal",
    "dolphin",
    "octopus",
    "squid",
    "lobster",
    "crab",
    "shrimp",
    "jellyfish",
    "seahorse",
    "starfish",
)

OBJECTS: tuple[str, ...] = (
    "pickle",
    "lantern",
    "bucket",
    "waffle",
    "sprocket",
    "thimble",
    "teapot",
    "trumpet",
    "shoebox",
    "briefcase",
    "umbrella",
    "telescope",
    "typewriter",
    "flashlight",
    "toaster",
    "microwave",
    "turnip",
    "radish",
    "pancake",
    "biscuit",
    "dumpling",
    "meatball",
    "sandwich",
    "pretzel",
    "muffin",
    "noodle",
    "spatula",
    "ladle",
    "whisk",
    "colander",
    "wheelbarrow",
    "traffic cone",
    "shopping cart",
    "rubber duck",
    "garden hose",
    "shoelace",
    "button",
    "marble",
    "pebble",
    "doorknob",
    "doorstop",
    "coat hanger",
    "clipboard",
    "stapler",
    "paperclip",
    "envelope",
    "notebook",
    "bookmark",
    "keyhole",
    "corkscrew",
    "thermos",
    "thermometer",
    "compass",
    "hourglass",
    "metronome",
    "kazoo",
    "trombone",
    "accordion",
    "harmonica",
    "calculator",
    "abacus",
    "floppy disk",
    "cassette",
    "joystick",
    "modem",
    "router",
    "antenna",
    "satellite",
    "moonbeam",
    "breadcrumb",
    "dust bunny",
    "sock",
    "slipper",
)

SCIENCE: tuple[str, ...] = (
    "paradox",
    "singularity",
    "anomaly",
    "particle",
    "neutrino",
    "quasar",
    "pulsar",
    "photon",
    "electron",
    "proton",
    "muon",
    "tachyon",
    "wormhole",
    "dimension",
    "continuum",
    "oscillation",
    "entropy",
    "gravity",
    "vacuum",
    "plasma",
    "isotope",
    "molecule",
    "organism",
    "mutation",
    "specimen",
    "artifact",
    "phenomenon",
    "conundrum",
    "hypothesis",
    "theorem",
    "algorithm",
    "protocol",
    "variable",
    "constant",
    "equation",
    "function",
    "iteration",
    "recursion",
    "exception",
    "compiler",
    "daemon",
    "process",
    "socket",
    "packet",
    "payload",
    "checksum",
)

PLACES: tuple[str, ...] = (
    "Harbor",
    "Station",
    "Junction",
    "Valley",
    "Canyon",
    "Meadow",
    "Marsh",
    "Swamp",
    "Island",
    "Peninsula",
    "Outpost",
    "Observatory",
    "Laboratory",
    "Basement",
    "Attic",
    "Pantry",
    "Garage",
    "Shed",
    "Bunker",
    "Lighthouse",
    "Watchtower",
    "Depot",
    "Terminal",
    "Arcade",
    "Library",
    "Cafeteria",
    "Diner",
    "Motel",
    "Laundromat",
    "Gas Station",
    "Rest Stop",
    "Truck Stop",
    "Parking Lot",
    "Food Court",
    "Waiting Room",
    "Break Room",
    "Server Room",
    "Boiler Room",
    "Mailroom",
    "Closet",
)

_NOUNS_AND_SCIENCE = OBJECTS + SCIENCE

_MAX_ATTEMPTS = 200
_ERROR = "could not generate a unique podcast name"


def generate_name(
    existing_names: set[str] | frozenset[str] = frozenset(),
    rng: random.Random | None = None,
) -> str:
    """Return a random, weighted two-word podcast name not in ``existing_names``.

    Pattern frequency: Adjective + Animal about 60% of the time, Adjective +
    Object about 25%, and a combined Objects-and-Science noun + Place about
    15%. Words are drawn via ``rng.choice`` and the final result is Title
    Cased. When ``rng`` is None the stdlib ``random`` module's globals are
    used; callers wanting determinism pass a seeded ``random.Random``.

    If every attempt collides with ``existing_names``, a ``RuntimeError`` is
    raised after 200 tries.
    """
    if rng is None:
        rng = random
    for _ in range(_MAX_ATTEMPTS):
        roll = rng.random()
        if roll < 0.60:
            name = f"{rng.choice(ADJECTIVES)} {rng.choice(ANIMALS)}"
        elif roll < 0.85:
            name = f"{rng.choice(ADJECTIVES)} {rng.choice(OBJECTS)}"
        else:
            name = f"{rng.choice(_NOUNS_AND_SCIENCE)} {rng.choice(PLACES)}"
        name = name.title()
        if name not in existing_names:
            return name
    raise RuntimeError(_ERROR)